version: '3'
services:
  java:
    image: openjdk:8-jdk-slim
    container_name: java-container
    working_dir: /usr/data
    volumes:
      - ./fibonacci-1.0-SNAPSHOT.jar:/usr/data/fibonacci-1.0-SNAPSHOT.jar
    ports:
      - "8080:8080"
    command: ["nohup", "java", "-jar", "fibonacci-1.0-SNAPSHOT.jar", "server", "&"]
  nginx:
    image: nginx:latest
    container_name: nginx-container
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./fibonacci:/usr/share/nginx/html
    ports:
      - "8000:8000"
    command: ["nginx", "-g", "daemon off;", "-c", "/etc/nginx/nginx.conf"]