version: '3'
services:
  
  nginx:
    image: nginx:latest
    container_name: nginx-container
    volumes:
      - /usr/data/nginx.conf:/etc/nginx/nginx.conf
      - /usr/data/html:/usr/share/nginx/html
    ports:
      - "8000:8000"
    command: ["nginx", "-g", "daemon off;", "-c", "/etc/nginx/nginx.conf"]

  java:
    image: openjdk:8-jdk-slim
    container_name: java-container
    volumes:
      - /usr/data/fibonacci-1.0-SNAPSHOT.jar:/usr/data/fibonacci-1.0-SNAPSHOT.jar
    ports:
      - "8080:8080"
    command: ["nohup", "java", "-jar", "/usr/data/fibonacci-1.0-SNAPSHOT.jar", "server"]