#server:
#  applicationConnectors:
#    - type: http
#      port: 8084
#configFilePath: ./config.yml
#logging:
#  level: INFO
#  loggers:
#    com.zuo: DEBUG

server:
  applicationConnectors:
    - type: http
      port: 8080
  adminConnectors:
    - type: http
      port: 8081
configFilePath: ./config.yml
logging:
  level: INFO
  loggers:
    com.zuo: DEBUG